# Generated by Django 3.2.20 on 2023-08-25 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('MO', 'Morestudents'), ('CU', 'Curriculum'), ('PR', 'Professor'), ('ET', 'Etc')], max_length=2)),
                ('content', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('CU', 'Current'), ('EN', 'End')], max_length=2)),
                ('created_at', models.DateTimeField()),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
