# Generated by Django 4.2.2 on 2023-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_posts_status_alter_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='duration',
            field=models.IntegerField(default=30),
        ),
    ]
